spring.application.name=Servidor
server.port = 8080

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_concursos
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.user.name=${LOGIN_USER}
spring.security.user.password=${LOGIN_PASSWORD}