spring.application.name=Cliente
server.port=8090

#Para que no intente crear la BD
spring.main.web-application-type=servlet
spring.datasource.initialize=false
spring.jpa.hibernate.ddl-auto=none
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


spring.mvc.log-request-details=true
logging.level.org.springframework.web=DEBUG